# Generated by Django 5.0.6 on 2024-05-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('sexe', models.CharField(max_length=100)),
                ('cv', models.ImageField(upload_to='images/')),
                ('photo', models.ImageField(upload_to='images/')),
                ('experience', models.CharField(max_length=100)),
                ('cartier', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('confirmé', 'Confirmé'), ('non confirmé', 'Non confirmé')], default='non confirmé', max_length=100)),
                ('categories', models.ManyToManyField(to='Enseignant.category')),
            ],
            options={
                'db_table': 'enseignant',
            },
        ),
    ]
