# Generated by Django 5.0.3 on 2024-03-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('matiere_principale', models.CharField(max_length=100)),
                ('competences_specifiques', models.TextField()),
                ('diplomes', models.TextField()),
                ('experience_professionnelle', models.TextField()),
                ('disponibilite', models.CharField(max_length=255)),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
